import type { Character } from "@/types";

export const character: Character = {
  name: "Luke Skywalker",
  height: "172",
  mass: "77",
  gender: "male",
  birth_year: "19BBY",
  hair_color: "blond",
  skin_color: "fair",
  eye_color: "blue",
};

export const characters: Character[] = [
  {
    name: "Luke Skywalker",
    height: "172",
    mass: "77",
    gender: "male",
    birth_year: "19BBY",
    hair_color: "blond",
    skin_color: "fair",
    eye_color: "blue",
    url: "https://swapi.dev/api/people/1/",
  },
  {
    name: "Darth Vader",
    height: "202",
    mass: "136",
    gender: "male",
    birth_year: "41.9BBY",
    hair_color: "none",
    skin_color: "white",
    eye_color: "yellow",
    url: "https://swapi.dev/api/people/4/",
  },
  {
    name: "Leia Organa",
    height: "150",
    mass: "49",
    gender: "female",
    birth_year: "19BBY",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    url: null,
  },
  {
    name: "Owen Lars",
    height: "178",
    mass: "120",
    gender: "male",
    birth_year: "52BBY",
    hair_color: "brown, grey",
    skin_color: "light",
    eye_color: "blue",
    url: "https://swapi.dev/api/people/6/",
  },
  {
    name: "Beru Whitesun lars",
    height: "165",
    mass: "75",
    gender: "female",
    birth_year: "47BBY",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "blue",
    url: "https://swapi.dev/api/people/7/",
  },
];
